local session = require("game.session")
local t = require("spec.support.runner")

t.describe("game session", function()
    t.it("builds requests and preserves player choices", function()
        local state = session.new()
        local ids = { "ozzo", "brakka", "rok_tann", "zyro_vex", "mika_olu" }
        assert(session.set_starters(state, ids))
        session.set_formation(state, "1-1-2")
        session.set_tactic(state, "press_high")
        local request = assert(session.build_request(state, 9))
        t.eq(request.home_starter_ids[5], "mika_olu")
        t.eq(request.formation_id, "1-1-2")
        t.eq(request.tactic_id, "press_high")
        t.eq(request.show_onboarding, true)
        t.eq(request.combat_enabled, false)
        session.set_combat_enabled(state, true)
        t.eq(assert(session.build_request(state, 10)).combat_enabled, true)
        state.first_match = false
        t.eq(assert(session.build_request(state, 10)).show_onboarding, false)
    end)

    t.it("maps result actions without mutating setup", function()
        local state = session.new()
        local original = state.starter_ids[1]
        t.eq(session.route_for_result("rematch"), "match")
        t.eq(session.route_for_result("change_plan"), "formation")
        t.eq(session.route_for_result("change_lineup"), "squad")
        t.eq(session.route_for_result("main_menu"), "title")
        t.eq(state.starter_ids[1], original)
    end)
end)
