// Verbatim copy of
// ../../fixtures/input_sample_vector.txt, generated by
// rust/crates/gc-sim/tests/input_sample_vector_generator.rs -- see that
// file's module doc for the generation command and this vector's
// rationale. Embedded as a TS string (rather than read from disk with
// `node:fs`) because this workspace's per-package pnpm isolation does not
// currently expose `@types/node` to `@gc/input` (`tsc --build` reports
// "Cannot find name 'node:fs'" et al.), and this package's task brief
// forbids touching `package.json` to add it -- the same finding and the
// same fix `@gc/render`'s `frame_buffer.spec.ts` already used for its own
// fixture; see that file's header for the precedent.
//
// Keep this byte-for-byte identical to the `.txt` original; do not
// hand-edit. Both files exist because the task brief asked for "a
// fixtures/vector file under ts/packages/input/" specifically -- the
// `.txt` is that file and stays the human-readable, diffable source of
// truth; this `.ts` is only how the spec reads it without `node:fs`.

export const INPUT_SAMPLE_VECTOR = `
# Cross-language vector for gc_sim::input_frame::InputSample's quantization
# and bit-packing rules, generated by this file. See its module doc for
# the generation command and rationale.
#
# Format: one field per non-comment, non-blank line, tab-separated:
#   field_name<TAB>value
# Cases are separated by a blank line, each opened by a \`case\` line.
# \`held_actions\`/\`edge_actions\` are comma-joined canonical action names
# (empty when none); \`move_x\`/\`move_y\`/\`held\`/\`edges\` are the expected
# InputSample fields \`gc_sim::input_frame::new_sample\` produced from
# quantizing raw_move_x/raw_move_y and packing held_actions/edge_actions'
# bits. raw_move_x/raw_move_y use Rust's default f64 Display (shortest
# round-trippable decimal) rather than %.17g -- simpler to generate
# correctly and an equal-or-stronger round-trip guarantee: every value
# here parses back to the identical f64 bit pattern via both Rust's
# f64::from_str and JavaScript's Number(). move_x/move_y/held/edges are
# plain integers (every one of them is i64 here).

case	neutral
raw_move_x	0
raw_move_y	0
held_actions
edge_actions
move_x	0
move_y	0
held	0
edges	0

case	axis_positive_half
raw_move_x	0.5
raw_move_y	0
held_actions
edge_actions
move_x	64
move_y	0
held	0
edges	0

case	axis_negative_half
raw_move_x	-0.5
raw_move_y	0
held_actions
edge_actions
move_x	-64
move_y	0
held	0
edges	0

case	axis_clamped_high
raw_move_x	2.5
raw_move_y	1
held_actions
edge_actions
move_x	127
move_y	127
held	0
edges	0

case	axis_clamped_low
raw_move_x	-3.7
raw_move_y	-1
held_actions
edge_actions
move_x	-127
move_y	-127
held	0
edges	0

case	axis_rounds_to_zero
raw_move_x	0.001
raw_move_y	-0.001
held_actions
edge_actions
move_x	0
move_y	0
held	0
edges	0

case	held_shoot
raw_move_x	0
raw_move_y	0
held_actions	shoot
edge_actions
move_x	0
move_y	0
held	1
edges	0

case	held_pass
raw_move_x	0
raw_move_y	0
held_actions	pass
edge_actions
move_x	0
move_y	0
held	2
edges	0

case	held_sprint
raw_move_x	0
raw_move_y	0
held_actions	sprint
edge_actions
move_x	0
move_y	0
held	4
edges	0

case	held_jockey
raw_move_x	0
raw_move_y	0
held_actions	jockey
edge_actions
move_x	0
move_y	0
held	8
edges	0

case	held_lob
raw_move_x	0
raw_move_y	0
held_actions	lob
edge_actions
move_x	0
move_y	0
held	16
edges	0

case	held_aerial_strike
raw_move_x	0
raw_move_y	0
held_actions	aerial_strike
edge_actions
move_x	0
move_y	0
held	32
edges	0

case	held_aerial_acrobatic
raw_move_x	0
raw_move_y	0
held_actions	aerial_acrobatic
edge_actions
move_x	0
move_y	0
held	64
edges	0

case	held_equipment
raw_move_x	0
raw_move_y	0
held_actions	equipment
edge_actions
move_x	0
move_y	0
held	128
edges	0

case	edge_shoot
raw_move_x	0
raw_move_y	0
held_actions
edge_actions	shoot
move_x	0
move_y	0
held	0
edges	1

case	edge_pass
raw_move_x	0
raw_move_y	0
held_actions
edge_actions	pass
move_x	0
move_y	0
held	0
edges	2

case	edge_switch
raw_move_x	0
raw_move_y	0
held_actions
edge_actions	switch
move_x	0
move_y	0
held	0
edges	4

case	edge_dash
raw_move_x	0
raw_move_y	0
held_actions
edge_actions	dash
move_x	0
move_y	0
held	0
edges	8

case	edge_dodge
raw_move_x	0
raw_move_y	0
held_actions
edge_actions	dodge
move_x	0
move_y	0
held	0
edges	16

case	equipment_pressed
raw_move_x	0
raw_move_y	0
held_actions	equipment
edge_actions	equipment_pressed
move_x	0
move_y	0
held	128
edges	32

case	equipment_released
raw_move_x	0
raw_move_y	0
held_actions
edge_actions	equipment_released
move_x	0
move_y	0
held	0
edges	64

case	equipment_fast_tap
raw_move_x	0
raw_move_y	0
held_actions
edge_actions	equipment_pressed,equipment_released
move_x	0
move_y	0
held	0
edges	96

case	all_held
raw_move_x	0
raw_move_y	0
held_actions	shoot,pass,sprint,jockey,lob,aerial_strike,aerial_acrobatic,equipment
edge_actions
move_x	0
move_y	0
held	255
edges	0

case	all_edges
raw_move_x	0
raw_move_y	0
held_actions
edge_actions	shoot,pass,switch,dash,dodge,equipment_pressed,equipment_released
move_x	0
move_y	0
held	0
edges	127

case	full_combo
raw_move_x	1
raw_move_y	-1
held_actions	shoot,pass,sprint,jockey,lob,aerial_strike,aerial_acrobatic,equipment
edge_actions	shoot,pass,switch,dash,dodge,equipment_pressed
move_x	127
move_y	-127
held	255
edges	63
`;
