//! Port of `game/online/input_protocol_fixture.lua`.
//!
//! The Lua original builds `session_id`/`manifest_id` from
//! `protocol_fixture.manifest()` and `protocol.manifest_id(manifest)`.
//! `protocol.lua` is out of scope for this agent (see the module doc comment
//! on [`crate::input_protocol`]), so this port uses the exact literal values
//! those calls are known to produce instead: `session_id = "session_alpha"`
//! (`game/online/protocol_fixture.lua:100`) and the manifest id embedded
//! verbatim in [`crate::input_protocol_conformance::GOLDEN`]'s pinned wire
//! literals (`"eb59f113614c35b2"`). Neither value needs `protocol.lua`'s
//! logic to reproduce: they are read as data, not computed. [`guest`] and
//! [`host`] therefore still exercise a real `packet_id` — an independent
//! check that this crate's `fnv1a64` and `packet_id` hashing agree with the
//! golden literal generated by the real Lua.
//!
//! [`maximal`] never depended on `protocol.lua` at all: the Lua original
//! already hardcodes its identity as literal strings.

use crate::input_protocol::{self, AuthorityRow, Packet, PacketOptions};
use gc_sim::input_frame::{self, InputSampleOptions};

/// Shared session identity the pinned conformance fixtures were generated
/// against. See the module doc comment for why this is a literal rather than
/// a call into `protocol_fixture`.
const SESSION_ID: &str = "session_alpha";
/// The manifest id embedded in the pinned golden wire literals.
const MANIFEST_ID: &str = "eb59f113614c35b2";

fn row(tick: i64, slot_index: i64, sample: input_frame::InputSample) -> AuthorityRow {
    AuthorityRow {
        tick,
        slot_index,
        sample,
    }
}

fn sample(options: InputSampleOptions) -> input_frame::InputSample {
    input_frame::new_sample(options).expect("fixture sample is always valid")
}

/// A guest packet carrying its current tick plus exactly six retained prior
/// rows, with distinct held/edge/axis combinations on every row, and a
/// nonzero confirmation span.
#[must_use]
pub fn guest() -> Packet {
    input_protocol::new_guest(PacketOptions {
        session_id: SESSION_ID.to_string(),
        manifest_id: MANIFEST_ID.to_string(),
        sender_id: "guest_2".to_string(),
        sequence: 7,
        transport_tick: 12,
        first_input_tick: 0,
        // Confirmation feedback: this guest has confirmed ticks 0..3.
        confirmed_span: Some(4),
        rows: vec![
            row(0, 2, input_frame::neutral_sample()),
            row(
                1,
                2,
                sample(InputSampleOptions {
                    move_x: Some(-127),
                    move_y: Some(127),
                    held: Some(input_frame::HELD_SHOOT + input_frame::HELD_SPRINT),
                    edges: Some(input_frame::EDGE_SHOOT + input_frame::EDGE_DASH),
                }),
            ),
            row(
                2,
                2,
                sample(InputSampleOptions {
                    held: Some(input_frame::HELD_EQUIPMENT),
                    edges: Some(input_frame::EDGE_EQUIPMENT_PRESSED),
                    ..Default::default()
                }),
            ),
            row(
                3,
                2,
                sample(InputSampleOptions {
                    held: Some(input_frame::HELD_EQUIPMENT),
                    ..Default::default()
                }),
            ),
            row(
                4,
                2,
                sample(InputSampleOptions {
                    edges: Some(input_frame::EDGE_EQUIPMENT_RELEASED),
                    ..Default::default()
                }),
            ),
            row(
                5,
                2,
                sample(InputSampleOptions {
                    held: Some(127),
                    edges: Some(31),
                    ..Default::default()
                }),
            ),
            row(
                6,
                2,
                sample(InputSampleOptions {
                    move_x: Some(127),
                    move_y: Some(-127),
                    held: Some(input_frame::HELD_PASS + input_frame::HELD_LOB),
                    edges: Some(
                        input_frame::EDGE_PASS + input_frame::EDGE_SWITCH + input_frame::EDGE_DODGE,
                    ),
                }),
            ),
        ],
    })
    .expect("input protocol fixture guest packet is always valid")
}

/// A host packet carrying two ticks across every canonical slot, with the
/// last slot's held/edge masks set to the equipment bits and every other
/// slot's masks derived from its slot index.
#[must_use]
pub fn host() -> Packet {
    let mut rows = Vec::new();
    for tick in 5..=6 {
        for slot_index in 1..=input_frame::SLOT_COUNT {
            let held = if slot_index == 8 {
                input_frame::HELD_EQUIPMENT
            } else {
                slot_index - 1
            };
            let edges = if slot_index == 8 {
                input_frame::EDGE_EQUIPMENT_PRESSED
            } else {
                slot_index - 1
            };
            rows.push(row(
                tick,
                slot_index,
                sample(InputSampleOptions {
                    move_x: Some(tick * 10 - slot_index),
                    move_y: Some(slot_index - tick * 10),
                    held: Some(held),
                    edges: Some(edges),
                }),
            ));
        }
    }
    input_protocol::new_host(PacketOptions {
        session_id: SESSION_ID.to_string(),
        manifest_id: MANIFEST_ID.to_string(),
        sender_id: "host".to_string(),
        sequence: 13,
        transport_tick: 15,
        first_input_tick: 0,
        // The host reports its own confirmation back the same way a guest does.
        confirmed_span: Some(5),
        rows,
    })
    .expect("input protocol fixture host packet is always valid")
}

/// The largest `first_input_tick` that still leaves a ten-digit
/// `confirmed_span`: pushing `first_input_tick` to [`input_frame::MAX_TICK`]
/// would collapse the span to a single digit and understate the header, so
/// this is the real ceiling for [`maximal`]'s worst-case header size.
pub const FIRST_INPUT_TICK: i64 = 1_000_000_000;

/// The largest host batch the wire format admits, and the packet the byte
/// budget is measured against: every variable-width header field at its
/// worst case simultaneously.
#[must_use]
pub fn maximal() -> Packet {
    let mut rows = Vec::new();
    let span = input_protocol::HOST_WINDOW_ROWS;
    for tick in (input_frame::MAX_TICK - span + 1)..=input_frame::MAX_TICK {
        for slot_index in 1..=input_frame::SLOT_COUNT {
            rows.push(row(
                tick,
                slot_index,
                sample(InputSampleOptions {
                    move_x: Some(127),
                    move_y: Some(-127),
                    held: Some(255),
                    edges: Some(input_frame::EDGE_EQUIPMENT_PRESSED),
                }),
            ));
        }
    }
    input_protocol::new_host(PacketOptions {
        session_id: "s".repeat(128),
        manifest_id: "0123456789abcdef".to_string(),
        sender_id: "h".repeat(128),
        sequence: 2_147_483_647,
        transport_tick: input_frame::MAX_TICK,
        first_input_tick: FIRST_INPUT_TICK,
        confirmed_span: Some(input_frame::MAX_TICK - FIRST_INPUT_TICK + 1),
        rows,
    })
    .expect("input protocol fixture maximal packet is always valid")
}
