local t = require("spec.support.runner")
local camera = require("game.render.camera")

local field = { w = 960, h = 540 }
local vp = { w = 1280, h = 720 }

t.describe("camera.project", function()
    t.it("places nearer points lower on screen than far points", function()
        local _, far_y = camera.project(480, 0, field, vp)
        local _, near_y = camera.project(480, 540, field, vp)
        t.is_true(near_y > far_y)
    end)

    t.it("scales nearer points up relative to far points", function()
        local _, _, far_scale = camera.project(480, 0, field, vp)
        local _, _, near_scale = camera.project(480, 540, field, vp)
        t.is_true(near_scale > far_scale)
    end)

    t.it("keeps the pitch centre line on the screen centre at any depth", function()
        local far_x = camera.project(480, 0, field, vp)
        local near_x = camera.project(480, 540, field, vp)
        t.near(far_x, vp.w / 2, 1e-6)
        t.near(near_x, vp.w / 2, 1e-6)
    end)

    t.it("spreads the near edge wider than the far edge (trapezoid)", function()
        local far_right = camera.project(960, 0, field, vp)
        local near_right = camera.project(960, 540, field, vp)
        t.is_true(near_right > far_right)
    end)
end)

t.describe("camera.window", function()
    t.it("zoom 1 frames the whole pitch regardless of focus", function()
        local w = camera.window(120, 90, field, 1)
        t.eq(w.x, 0)
        t.eq(w.y, 0)
        t.eq(w.w, 960)
        t.eq(w.h, 540)
    end)

    t.it("centres on the focus point when there is room", function()
        local w = camera.window(480, 270, field, 2)
        t.eq(w.w, 480)
        t.eq(w.h, 270)
        t.eq(w.x, 240)
        t.eq(w.y, 135)
    end)

    t.it("clamps to the pitch so the view never leaves the touchline", function()
        local near = camera.window(0, 0, field, 2)
        t.eq(near.x, 0)
        t.eq(near.y, 0)
        local far = camera.window(960, 540, field, 2)
        t.eq(far.x, 480)
        t.eq(far.y, 270)
    end)

    t.it("projecting through a window magnifies the framed region", function()
        local w = camera.window(480, 270, field, 2)
        -- Two points a fixed world distance apart span more screen with the
        -- window than without it: that is what "closer" means here.
        local a = camera.project(400, 270, field, vp)
        local b = camera.project(560, 270, field, vp)
        local wa = camera.project(400, 270, field, vp, nil, w)
        local wb = camera.project(560, 270, field, vp, nil, w)
        t.is_true(math.abs(wb - wa) > math.abs(b - a), "windowed span should be wider")
    end)
end)
