// Lobby, signalling, session coordination, diagnostics.

export {
  type DiagnosticsDomain,
  type DiagnosticsField,
  type DiagnosticsFieldKind,
  type DiagnosticsShape,
  SERIALIZATION_VERSION,
  DIGEST,
  HASH_LENGTH,
  MAX_ID_LENGTH,
  MAX_STRING_LENGTH,
  MAX_TEXT_LENGTH,
  MAX_ARRAY_LENGTH,
  MAX_SAFE_INTEGER,
  TRUNCATED,
  COMPLETE,
  REDACTED,
  isSensitiveText,
  redactFreeText,
  isWallClockName,
  isSimulationName,
  record,
  nested,
  enumValues,
  validate,
  // Renamed to avoid colliding with `net_diagnostics`'s artifact-level
  // `encode`/`digest`, which most callers of this package actually want.
  encode as encodeCanonicalValue,
  digest as digestCanonicalValue,
  tupleDigest,
  project,
  domains,
} from "./diagnostics_schema.ts";

export {
  type SessionRole,
  type MatchMode,
  type CombatMatchStatus,
  type MatchDriverStatus,
  type CoordinatorNetcodeFailure,
  type SessionMessageKind,
  type NetDiagnosticsRetention,
  type NetDiagnosticsSignalDirection,
  type NetDiagnosticsPacketDisposition,
  type NetDiagnosticsEventKind,
  type SessionManifest,
  type CoordinatorFreeze,
  type MatchDriverTerminal,
  type MatchDriverDiagnostics,
  type DiagnosticEventFieldValue,
  type DiagnosticEvent,
  type RollbackTickOutput,
  type MatchDriverCheckpoint,
  type MatchDriverBatch,
  type ProtocolControlMessage,
  type ProtocolDecoder,
  type NetDiagnosticsLimits,
  type NetDiagnosticsOptions,
  type NetDiagnosticsCheckpointRecord,
  type NetDiagnosticsMismatchRecord,
  type NetDiagnosticsPacketRecord,
  type NetDiagnosticsPacketInput,
  type NetDiagnosticsControlRecord,
  type NetDiagnosticsEventRecord,
  type NetDiagnosticsEventInput,
  type NetDiagnosticsSignalRecord,
  type NetDiagnosticsRuntimeSample,
  type NetDiagnosticsAnchorInput,
  type NetDiagnosticsTeardownInput,
  type NetDiagnostics,
  SCHEMA_VERSION,
  DEFAULT_LIMITS,
  MAX_DETAIL_BYTES,
  SESSION_SHAPE,
  EXPORT,
  CANONICAL_PROJECTION,
  newNetDiagnostics,
  optInExport,
  optOutExport,
  recordStep,
  recordCheckpoint,
  recordMismatch,
  recordPacket,
  recordControl,
  recordTransport,
  recordRuntimeSample,
  recordAnchor,
  recordEvent,
  recordSignal,
  recordTeardown,
  exportArtifact,
  encode,
  digest,
  canonicalBytes,
  canonicalDigest,
  summary,
} from "./net_diagnostics.ts";

export { type DiagnosticTransportOptions, DiagnosticTransport } from "./diagnostic_transport.ts";

export {
  type LobbyFrameBuffer,
  type LobbyLinkEvent,
  type LobbyEffect,
  FRAME_PREFIX,
  MAX_CHUNK_BYTES,
  MAX_FRAMES,
  frame,
  newFrameBuffer,
  absorb,
  LobbyLink,
  newLobbyLink,
} from "./lobby_link.ts";

export {
  type OpaqueSnapshot,
  // Renamed: these are this module's own narrow, "only fields read"
  // duplicates of the same Rust-owned shapes `net_diagnostics` declares
  // (see match_presentation.ts's boundary note) -- deliberately different
  // subsets, not the same type.
  type RollbackTickOutput as MatchPresentationTickOutput,
  type MatchDriverBatch as MatchPresentationDriverBatch,
  type SnapshotLookup,
  type MatchDriverPort,
  type RollbackEventStepInput,
  type RollbackWrappedEvent,
  type RollbackEventReplacement,
  type RollbackEventDiff,
  type RollbackEventsStatus,
  type RollbackEventsDiagnostics,
  type RollbackConfirmedStateView,
  type RollbackEventStep,
  type RollbackApplyFailure,
  type RollbackApplyResult,
  type RollbackEventsPort,
  type RollbackPlayableLabStatus,
  type RollbackPlayableCorrection,
  type RollbackPlayableLabBatch,
  type OnlineMatchPresentation,
  type MatchPresentationPorts,
  newOnlineMatchPresentation,
  consume as consumeMatchPresentationBatch,
  diagnostics as matchPresentationDiagnostics,
  status as matchPresentationStatus,
} from "./match_presentation.ts";

export {
  type FaultHarnessTopology,
  type SessionMatchMode,
  type FaultScenario,
  type FaultFinding,
  type FaultReport,
  type FaultRunOptions,
  type FaultScenariosPort,
  type FaultCampaignOptions,
  MARKER_VERSION,
  PROBE_KEYS,
  hashOrderProbe,
  main as runFaultCampaign,
  runSelection as runFaultCampaignSelection,
} from "./fault_campaign.ts";

// Namespaced rather than flattened: its verbs (`run`, `advance`, `peer`,
// `harness`, `quality`) are too generic to export bare from a package
// barrel, and its own `MatchDriverPort` is unrelated to (and would
// otherwise collide with) `match_presentation.ts`'s port of the same name.
export * as netDiagnosticsFixture from "./net_diagnostics_fixture.ts";
