//! Embed the Lua tree into the binary (#334).
//!
//! #327 shipped the Lua sources as an Emscripten `--preload-file` package: a
//! second 3.2 MB artifact to deploy beside the .wasm, kept in sync by hand, and
//! mounted into a virtual filesystem before the first tick could run. This
//! build script removes both costs by turning the tree into an `include_str!`
//! table that the host resolves `require` against directly.
//!
//! The tree WALKS; it is never listed. A hand-maintained manifest would make
//! adding a `sim/` module a two-file change and would go stale silently -- the
//! failure mode being a module that exists natively and is missing in the
//! browser. `cargo:rerun-if-changed` is emitted for every directory and every
//! file, so an edit, an addition or a deletion all force a rebuild.
//!
//! Nothing under `core/`, `data/` or `sim/` is read for anything but its bytes.
//! Those layers stay unmodified and remain the single source of truth.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// Directory roots walked for `.lua` files, relative to the repository root.
/// These are the layers the probe requires: the pure trio plus the probe's own
/// home. Everything else in the repository needs LOVE and cannot run here.
const ROOTS: [&str; 4] = ["core", "data", "scripts", "sim"];

fn main() {
    let manifest = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("cargo always sets CARGO_MANIFEST_DIR"),
    );
    let repo_root = manifest
        .ancestors()
        .nth(2)
        .expect("crate should sit two levels below the repository root");

    let mut sources: Vec<(String, PathBuf)> = Vec::new();
    for root in ROOTS {
        collect(&repo_root.join(root), repo_root, &mut sources);
    }
    assert!(
        !sources.is_empty(),
        "no Lua sources found under {}; is the repository root wrong?",
        repo_root.display()
    );
    // Sorted so the generated table -- and with it the binary -- does not
    // depend on directory iteration order, and so the host can binary search.
    sources.sort();

    let mut generated = String::from("// @generated by build.rs (#334) -- do not edit.\n");
    generated.push_str("/// Repository-relative path -> source text, sorted by path.\n");
    generated.push_str("pub static SOURCES: &[(&str, &str)] = &[\n");
    for (path, absolute) in &sources {
        let absolute = absolute.to_str().expect("source path should be UTF-8");
        // `{:?}` on a &str emits a correctly escaped Rust string literal.
        writeln!(generated, "    ({path:?}, include_str!({absolute:?})),")
            .expect("writing to a String cannot fail");
    }
    generated.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("cargo always sets OUT_DIR"));
    let destination = out_dir.join("embedded_lua.rs");
    fs::write(&destination, generated)
        .unwrap_or_else(|error| panic!("write {}: {error}", destination.display()));

    println!("cargo:rerun-if-changed=build.rs");
}

/// Recursively gather `.lua` files, recording each as (repo-relative path,
/// absolute path) and registering both directories and files for rebuild.
fn collect(directory: &Path, repo_root: &Path, out: &mut Vec<(String, PathBuf)>) {
    // A directory's own mtime changes when a file is added or removed, which is
    // how a deleted module stops being embedded without a `cargo clean`.
    println!("cargo:rerun-if-changed={}", directory.display());

    let entries = fs::read_dir(directory)
        .unwrap_or_else(|error| panic!("read {}: {error}", directory.display()));
    for entry in entries {
        let path = entry.expect("directory entry should be readable").path();
        if path.is_dir() {
            collect(&path, repo_root, out);
        } else if path.extension().is_some_and(|extension| extension == "lua") {
            println!("cargo:rerun-if-changed={}", path.display());
            let relative = path
                .strip_prefix(repo_root)
                .expect("walked paths live under the repository root")
                .to_str()
                .expect("source path should be UTF-8")
                .replace(std::path::MAIN_SEPARATOR, "/");
            out.push((relative, path));
        }
    }
}
