// The authored network condition profiles, restated for the browser.
//
// THE SOURCE OF TRUTH IS RUST. These four profiles are authored in
// `rust/crates/gc-data/src/network_profiles.rs` and are what
// `gc_sim::rollback_lab` drives the native rollback matrix with. Browser
// evidence that impairs traffic with different numbers measures a different
// thing and cannot be compared to the native run at all -- so the numbers
// below are not "the browser's copy", they are an ASSERTED mirror.
//
// ARCHITECTURE.md §4 rule 6 forbids duplicating a `gc-data` table into
// TypeScript and allows a carve-out only when the duplicate lands together
// with a cross-language assertion wired into the gate. That assertion is
// `scripts/check_network_profile_parity.mjs`, gate 0c of
// `./scripts/check.sh`: it reads the Rust table and this file and requires
// every profile, every field and every value to agree. Do not edit this file
// without editing the Rust table, and do not silence the gate -- a browser
// soak run that impaired a "stress" link at half the authored loss rate
// would report a clean hour and prove nothing.
//
// The alternative -- reading the values through the wasm bridge at runtime,
// which would make the duplicate impossible rather than merely detectable --
// is the better long-term answer and is not taken here: nothing in
// `gc-wasm` exports the profile table today, and the impairment decorator
// must also run in a plain Node vitest process with no wasm loaded.

/** The authored profile names, matching `NetworkProfileName` in gc-data. */
export type NetworkProfileName = "clean" | "omp0_parity" | "playable" | "stress";

/**
 * One simulated network condition profile. Field for field the shape
 * `gc_data::network_profiles::NetworkProfile` authors, minus its `name`,
 * which is the key here.
 */
export interface NetworkProfile {
  /** Fixed delay, in ticks. */
  readonly base_delay_ticks: number;
  /** Minimum jitter added to the delay, in ticks. */
  readonly jitter_min_ticks: number;
  /** Maximum jitter added to the delay, in ticks. */
  readonly jitter_max_ticks: number;
  /** Probability a packet is independently lost. */
  readonly independent_loss_rate: number;
  /** Probability a packet is duplicated. */
  readonly duplication_rate: number;
  /** Probability a loss burst starts on a given tick. */
  readonly burst_start_rate: number;
  /** Length of a loss burst, in ticks. */
  readonly burst_length_ticks: number;
}

/** Every authored network profile, keyed by name. */
export const NETWORK_PROFILES: Readonly<Record<NetworkProfileName, NetworkProfile>> = {
  clean: {
    base_delay_ticks: 0,
    jitter_min_ticks: 0,
    jitter_max_ticks: 0,
    independent_loss_rate: 0.0,
    duplication_rate: 0.0,
    burst_start_rate: 0.0,
    burst_length_ticks: 0,
  },
  omp0_parity: {
    base_delay_ticks: 3,
    jitter_min_ticks: 0,
    jitter_max_ticks: 0,
    independent_loss_rate: 0.01,
    duplication_rate: 0.0,
    burst_start_rate: 0.0,
    burst_length_ticks: 0,
  },
  playable: {
    base_delay_ticks: 3,
    jitter_min_ticks: -2,
    jitter_max_ticks: 2,
    independent_loss_rate: 0.01,
    duplication_rate: 0.0025,
    burst_start_rate: 0.0025,
    burst_length_ticks: 3,
  },
  stress: {
    base_delay_ticks: 6,
    jitter_min_ticks: -3,
    jitter_max_ticks: 3,
    independent_loss_rate: 0.03,
    duplication_rate: 0.01,
    burst_start_rate: 0.01,
    burst_length_ticks: 3,
  },
};

/** Every authored profile name, in the order gc-data declares them. */
export const NETWORK_PROFILE_NAMES: readonly NetworkProfileName[] = [
  "clean",
  "omp0_parity",
  "playable",
  "stress",
];

/** Look up an authored network profile by name. */
export function networkProfile(name: NetworkProfileName): NetworkProfile {
  return NETWORK_PROFILES[name];
}
